name: xclean
description: Aplicativo de agendamento de serviços de limpeza.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  image_picker: ^1.0.0
  cached_network_image: ^3.2.0
  flutter_mask: ^2.0.0
  google_maps_flutter: ^2.3.0
  geolocator: ^9.0.2
  url_launcher: ^6.1.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.0.5
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700 